library(TransmitTestandCull)
library(dplyr)
library(quantreg)
library(metafor)
library(ggplot2)

source("fit_qribbons.R")
source("plot_data_comparison.R")

# The code here would generate Figs 1 and 2. Figs 3 and 4 are just the same bit with a lower value
# for sensitivity_latent in the params list and the relevant results file loaded.

params <- list(
  N0 = NULL,
  initial_prevalence = NULL,
  sensitivity_infectious = 0.76,
  sensitivity_latent = 0.76/2,
  specificity = 0.998,
  prop_infectious = 0.25,
  scanning_timepoints = NULL,
  time_between_restocking = 365,
  R0 = NULL,
  mu_L = 180,
  sh_L = 30,
  mu_I = 90,
  sh_I = 10
)

# This loads the field data for plotting. This data is generated by estimate_field_prevalences.R based on the data
# in processed_OPA_data.csv
load("../Data/opa_dat.Rdata")
# This loads in the model simulation results which are generated by opa_sim.R which is then passed through combine_results.R
# Note that opa_sim.R is set up to run the model on a high performance computer cluster because this paper uses
# very large numbers of simulations as part of the ABC rejection sampling. It is possible to simulate the model much more
# straightforwardly on a personal computer by downloading and installing the R package supplied.
all_results <- readRDS("../Results/all_results_onlyR0.rds")

# Ok, having looked at this a bit we just aren't getting useful results when there are only 2 scans, which isn't surprising.
# If there's an increase in positives or things are stagnant between the scans we are getting R0s that are unbelievably large and if it
# decreases they are tiny. So I'm going to filter our the farms with only 2 scans.


removed_uids <- opa_dat %>%
  group_by(UID) %>%
  summarise(
    keep = any(pos != 0) & first(N.scans) >= 3,
    .groups = "drop"
  ) %>%
  filter(!keep) %>%
  pull(UID)

opa_dat <- opa_dat %>%
  filter(!UID %in% removed_uids)



all_results <- all_results[!(all_results$UID %in% removed_uids),]

# Now we extract the 1000 (1%) simulations with the lowest RMSE when compared with the farm scanning
# data (done on a logit scale) and create some summaries
all_results_rmse_logit <- all_results %>%
  group_by(UID) %>%
  slice_min(order_by = RMSE.logit, n = 1000, with_ties = FALSE) %>%
  summarise(R0.median = median(R0),
            R0.lwr = quantile(R0, 0.025),
            R0.upr = quantile(R0, 0.975))

# Calculate how many scans were applied on each farm for plotting. Create a factor that has categories based on number of scans applied.
# Order based on number of scans for plotting.
all_results_rmse_logit$Nscans <- NA
for(i in 1:length(all_results_rmse_logit$UID)){
  all_results_rmse_logit$Nscans[i] <- opa_dat[opa_dat$UID == all_results_rmse_logit$UID[i],]$N.scans
}
all_results_rmse_logit$Nscans.f <- ifelse(all_results_rmse_logit$Nscans >= 10, ">=10", ifelse(all_results_rmse_logit$Nscans >= 5, "5-9", "<5"))
all_results_rmse_logit$Nscans.f <- factor(all_results_rmse_logit$Nscans.f, levels = c(">=10", "5-9", "<5"))
all_results_rmse_logit$UID <- factor(all_results_rmse_logit$UID,
                                     levels = all_results_rmse_logit %>%
                                       arrange(Nscans.f, desc(R0.median)) %>%
                                       pull(UID))

# This makes Fig 1 (or 3)
p1.rmse.logit <- ggplot(all_results_rmse_logit, aes(x=UID, y=R0.median, col=Nscans.f)) +
  geom_pointrange(aes(ymin = R0.lwr, ymax = R0.upr),
                  position = position_dodge(width = 0.9)) +
  theme_bw() +
  labs(col = "No. scans",
       x = "Farm ID",
       y = "R0") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size=12),
        axis.title=element_text(size=14),
        legend.text = element_text(size=12),
        legend.title = element_text(size=14)) +
  geom_hline(yintercept=1, linetype=2)

# Comparing using versus not using a logit transformation it doesn't make much difference to the estimates for most farms (which is good).
# On farms where there are scans with no positives then using the logit transformation can result in slightly higher R0 estimates. This
# makes sense to me because on farms with zeros and no logit transformation the cost of underestimating R0 (in terms of RMSE) will likely 
# be less than the cost of overestimating it because you can't go too low but you can go far too high.

# Save the plot
png("C:/Users/de43382/opa-stochastic-model/Figures/R0_values.png", width=9, height=6, units="in", res=600)
p1.rmse.logit
dev.off()

# This part is the part that makes Fig 2 (and 4)
all_results_thinned_rmse_logit <- all_results %>%
  group_by(UID) %>%
  slice_min(order_by = RMSE.logit, n = 1000, with_ties = FALSE)

abc_summary <- all_results_thinned_rmse_logit %>%
  group_by(UID) %>%
  summarise(SE = sd(R0)/sqrt(length(R0)),
            R0 = mean(R0)) 
res <- rma(yi = R0, sei = SE, method = "REML", data = abc_summary)
# Extract estimated population mean (mu) and between-UID tau
mu_hat  <- as.numeric(coef(res))     # population mean
tau_hat <- sqrt(res$tau2)            # between-UID SD

# For each farm UID we remove that from the estimation of a global R0 and then use the estimated R0 value to simulate multiple OPA trajectories.
# We then plot these trajectories against the scanning data to visualise how well the model has been able to predict the scan data.

plots <- vector("list", length(unique(opa_dat$UID)))
for(i in 1:length(unique(opa_dat$UID))){
  plots[[i]] <- plot_data_comparison(data=opa_dat, UID=unique(opa_dat$UID)[i], params=params, abc_results=all_results_thinned_rmse_logit, niter=250)
}

# This just performs some annotation and produces Fig 2 (and 4)
p.all <- ggarrange(plotlist=plots, legend = "none", align='v')
p.all <- annotate_figure(p.all, left = textGrob("Prevalence (%)", rot = 90, vjust = 1, gp = gpar(cex = 1.5)),
                         bottom = textGrob("Time (years)", gp = gpar(cex = 1.5)))
#png("C:/Users/de43382/opa-stochastic-model/Figures/LOO_validation.png", width=12, height=12, units="in", res=600)
p.all
#dev.off()