# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_OPA <- function(params, Tmax) {
    .Call(`_TransmitTestandCull_simulate_OPA`, params, Tmax)
}

